---

- hosts: all
  gather_facts: false
  tasks:
  include_vars: /Users/sea01/Documents/repos/sysadmin/ansible/dev/group_vars/dev-tomcat.yml

    - name: Copy Tomcat configuration files from templates
      template: src={{ item.src }} dest=/Users/sea01/Documents/repos/sysadmin/ansible/dev/group_vars/server.xml owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
      with_items: "{{ tomcat_configs }}"
